[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/takashiidobe/mcli:aarch64-unknown-linux-gnu"

[target.i686-unknown-linux-gnu]
image = "ghcr.io/takashiidobe/mcli:i686-unknown-linux-gnu"

[target.powerpc64le-unknown-linux-gnu]
image = "ghcr.io/takashiidobe/mcli:powerpc64le-unknown-linux-gnu"

[target.arm-unknown-linux-gnueabihf]
image = "ghcr.io/takashiidobe/mcli:arm-unknown-linux-gnueabihf"

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/takashiidobe/mcli:aarch64-unknown-linux-musl"

[target.s390x-unknown-linux-gnu]
image = "ghcr.io/takashiidobe/mcli:s390x-unknown-linux-gnu"

[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/takashiidobe/mcli:armv7-unknown-linux-gnueabihf"

[target.arm-unknown-linux-gnueabi]
image = "ghcr.io/takashiidobe/mcli:arm-unknown-linux-gnueabi"

[target.i686-unknown-linux-musl]
image = "ghcr.io/takashiidobe/mcli:i686-unknown-linux-musl"
