.TH MCLI 1
.SH NAME
mcli \- A music player cli in rust.
.SH SYNOPSIS
\fBmcli\fR path
.SH COMMANDS

v      Volume. Set the volume.

        


.SH EXIT STATUS
.TP
\fB0\fR
Successful program execution.

.TP
\fB1\fR
Unsuccessful program execution.

.TP
\fB101\fR
The program panicked.
.SH AUTHOR
.P
.RS 2
.nf
Takashi I <mail@takashiidobe.com>
