name: Create docker images 

on:
  push:
    # paths:
    #   - 'dockerfiles/**'

jobs:
  docker:
    strategy:
      matrix:
        target: [ 
          aarch64-unknown-linux-gnu,
          i686-unknown-linux-gnu,
          powerpc64le-unknown-linux-gnu,
          arm-unknown-linux-gnueabihf,
          aarch64-unknown-linux-musl,
          s390x-unknown-linux-gnu,
          armv7-unknown-linux-gnueabihf,
          arm-unknown-linux-gnueabi,
          i686-unknown-linux-musl
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: takashiidobe 
          password: ${{ secrets.GHCR_REGISTRY_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/${{ matrix.target }}/
          push: true 
          tags: |
            ghcr.io/takashiidobe/mcli:${{ matrix.target }}
